---

- hosts: linux_servers
  become: true
  tasks:



    - name: install apache and php packages
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: present
        update_cache: yes
