---
- hosts: linux_servers
  gather_facts: yes
  tasks:
    - name: Display Java installation path
      ansible.builtin.command: "readlink -f $(which java)"
      register: java_path

    - name: Show the Java installation path
      ansible.builtin.debug:
        msg: "Java is installed at {{ java_path.stdout }}"

  tasks:
    - name: Display Java 8 installation path
      debug:
        msg: "Java 8 je naistalovaná v: {{ansible_local.java_8.general.home }}"

    - name: Display Java 17 instalation path
      debug:
        msg: "Java 17 je nainstalovaná v: {{ansible_local.java_17.general.home }}"






